name: Build and Push Docker image

on:
  push:
    branches:
      - master
  release:
    types: [published, edited]

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/go-socks5-proxy

jobs:
  hadolint:
    name: Lint Dockerfile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run hadolint
        uses: hadolint/hadolint-action@v1.5.0
        with:
          ignore: DL3018

  build-and-push:
    name: Build and Push multi-arch Docker image
    runs-on: ubuntu-latest
    needs: hadolint
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'master') }}
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=sha

      - name: Build and Push Docker image (multi-arch)
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Print image info
        run: |
          echo "✅ Image pushed to ${{ env.IMAGE_NAME }} with tags:"
          echo "${{ steps.meta.outputs.tags }}"
